version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: author-articles-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: author-articles-db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    container_name: author-articles-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/author-articles-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - files-data:/files
    ports:
      - "8081:8080"

  frontend:
    image: nginx:alpine
    container_name: author-articles-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data:
  files-data:
