services:
  ### mysql ###################################################
  mysql:
    image: mysql
    container_name: ${DOCKER_PROJECT_NAME}-mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${DB_MYSQL_DOCKER_PORT}:${DB_MYSQL_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234" ]
      timeout: 20s
      retries: 10
    networks:
      - localnet
  ### mongodb ####################################################
  mongodb:
    image: mongo
    container_name: ${DOCKER_PROJECT_NAME}-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
    ports:
      - ${DB_MONGO_DOCKER_PORT}:${DB_MONGO_PORT}
    networks:
      - localnet
  ### spring ###################################################
  spring-boot-app:
    container_name: ${DOCKER_PROJECT_NAME}-spring-boot-app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - ${SPRING_DOCKER_PORT}:${SPRING_PORT}
    volumes:
      - ./src/main:/app/src/main
      - ./images:/app/images
    depends_on:
      - mysql
      - mongodb
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_MYSQL_URL: ${DB_MYSQL_URL}
      DB_MONGO_URL: ${DB_MONGO_URL}
      AZURE_BLOB_CONNECTION_STRING: ${AZURE_BLOB_CONNECTION_STRING}
      AZURE_BLOB_CONTAINER_NAME: ${AZURE_BLOB_CONTAINER_NAME}
      IMAGE_UPLOAD_DIR: ${SPRING_IMAGES_PATH}
    networks:
      - localnet
networks:
  localnet:
    driver: bridge