spring.application.name=author-articles-project

## MySQL Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/author-articles-db
spring.datasource.username=root
spring.datasource.password=root

##  Spring  ##
server.port=8085

# Redis
